const fs = require("fs");
const path = require("path");
const reportModel = require("../models/reportModel");
const assetModel = require("../models/assetModel");
const allocationModel = require("../models/allocationModel");
const maintenanceModel = require("../models/maintenanceModel");
const auditModel = require("../models/auditModel");
const bookingModel = require("../models/bookingModel");
const notificationModel = require("../models/notificationModel");
const { getUploadsDirectory } = require("../config/db");

function generateCode() {
  return `R${String(Date.now()).slice(-6)}`;
}

function toCsv(rows) {
  if (!rows.length) {
    return "No Data\n";
  }

  const headers = Object.keys(rows[0]);
  const lines = rows.map((row) =>
    headers
      .map((header) => {
        const value = row[header] ?? "";
        const text = String(value).replace(/"/g, '""');
        return `"${text}"`;
      })
      .join(",")
  );

  return `${headers.join(",")}\n${lines.join("\n")}\n`;
}

async function buildReportData(reportType) {
  switch (reportType) {
    case "Allocation Report":
      return allocationModel.listAllocations();
    case "Maintenance Report":
      return maintenanceModel.listMaintenanceRequests();
    case "Audit Report":
      return auditModel.listAudits();
    case "Booking Report":
      return bookingModel.listBookings();
    case "Asset Summary":
    default:
      return assetModel.listAssets();
  }
}

async function listReports(req, res) {
  const reports = await reportModel.listReports();
  return res.json(reports);
}

async function getSummary(req, res) {
  const summary = await reportModel.getSummaryCards();
  return res.json(summary);
}

async function getDistribution(req, res) {
  const distribution = await reportModel.getAssetDistribution();
  return res.json(distribution);
}

async function generateReport(req, res) {
  const {
    reportType = "Asset Summary",
    department = "All Departments",
    fromDate = null,
    toDate = null
  } = req.body;

  const reportData = await buildReportData(reportType);
  const code = generateCode();
  const fileName = `${code}-${reportType.toLowerCase().replace(/\s+/g, "-")}.csv`;
  const uploadsDirectory = getUploadsDirectory();
  const filePath = path.join(uploadsDirectory, fileName);
  const generatedBy = req.user.fullName || "Admin User";

  fs.mkdirSync(uploadsDirectory, { recursive: true });
  fs.writeFileSync(filePath, toCsv(reportData), "utf8");

  const report = await reportModel.createReport({
    code,
    reportName: reportType,
    reportType,
    departmentFilter: department,
    fromDate,
    toDate,
    generatedBy,
    format: "CSV",
    fileName,
    filePath
  });

  await notificationModel.createNotification({
    category: "System",
    message: `${reportType} was generated by ${generatedBy}.`,
    priority: "Low"
  });

  return res.status(201).json(report);
}

async function getReport(req, res) {
  const report = await reportModel.getReportById(req.params.id);

  if (!report) {
    return res.status(404).json({ message: "Report not found." });
  }

  return res.json(report);
}

async function downloadReport(req, res) {
  const report = await reportModel.getReportById(req.params.id);

  if (!report || !report.file_path || !fs.existsSync(report.file_path)) {
    return res.status(404).json({ message: "Report file not found." });
  }

  return res.download(report.file_path, report.file_name);
}

async function exportSummary(req, res) {
  const summary = await reportModel.getSummaryCards();
  const code = generateCode();
  const fileName = `${code}-asset-summary.csv`;
  const uploadsDirectory = getUploadsDirectory();
  const filePath = path.join(uploadsDirectory, fileName);
  const rows = [
    { metric: "Total Assets", value: summary.totalAssets || 0 },
    { metric: "Allocated", value: summary.allocated || 0 },
    { metric: "Available", value: summary.available || 0 },
    { metric: "Maintenance", value: summary.maintenance || 0 }
  ];

  fs.mkdirSync(uploadsDirectory, { recursive: true });
  fs.writeFileSync(filePath, toCsv(rows), "utf8");

  return res.download(filePath, fileName);
}

module.exports = {
  listReports,
  getSummary,
  getDistribution,
  generateReport,
  getReport,
  downloadReport,
  exportSummary
};
